### PR TITLE
Add includePatterns and excludePatterns support for copy

### PR DESCRIPTION
**Pull request by aaronlehmann**
Tested with:

```
fs busybox() {
        image "busybox"
}

fs copyWithPatterns() {
        copy busybox "/bin" "/" with option {
                includePatterns "x*"
                excludePatterns "xargs"
        }
        download "."
}
```

Depends on upstream PRs https://github.com/tonistiigi/fsutil/pull/101 and https://github.com/moby/buildkit/pull/2082

### CODE REVIEW

**Comment by coryb** [comment]
LGTM, think we just need to update generated content with `./hlb run -t gen`

**Comment by hinshun** [comment]
Overall looks good. Pending upstream PRs to be merged.

**Comment by aaronlehmann** [comment]
@hinshun: Updated.

**Review by hinshun — APPROVED** [review]
Tested myself, LGTM on test green

**Pull request merged**
